### PR TITLE
CG adding a slimmer imagenet for behavior

### PR DESCRIPTION
**Pull request by chongguo**

### CODE REVIEW

**Comment by stothe2** [comment]
Looks great! Ready to merge once bucket name is changed to `brainio.requested`. (You'll need to physically remove the stimuli from `brainio.dicarlo` on S3 too).

**Comment by stothe2** [comment]
@chongguo Chong, this is ready to merge, but you need to:
- [ ] Update the bucket name to `brainio.requested` in your packaging script, and run the script again.
- [ ] Remove previous changes to [`lookup.csv`.](https://github.com/brain-score/brainio_collection/pull/55/files)

**Comment by chongguo** [comment]
wait Martin told me to use brainio.dicarlo ... why should it be in requested?

**Comment by stothe2** [comment]
We're using the S3 buckets as so:
image

**Review by stothe2 — APPROVED** [review]

**Pull request merged**
